// <auto-generated />
using BussinessLayer.Interfaces;
using Common_Layer.Models;
using RepositoryLayer.Interfaces;
using System;
using System.Collections.Generic;
using System.Text;

namespace BussinessLayer.Services
{
    public class AdminBL : IAdminBL
    {

        readonly IAdminRL adminRL;
        public AdminBL(IAdminRL adminRL)
        {
            this.adminRL = adminRL;
        }
        public Admin Authenticate(string Email, string Password)
        {
            try
            {
                return adminRL.Authenticate(Email, Password);
            }
            catch (Exception a)
            {
                throw a;
            }
        }
    }
}
