// <auto-generated />
using BussinessLayer.Interfaces;
using Common_Layer.Models;
using CommonLayer.Models;
using RepositoryLayer.Interfaces;
using System;
using System.Collections.Generic;
using System.Text;

namespace BussinessLayer.Services
{
    public class UserBL : IUserBL

    {
        readonly IUserRL userRL;
        public UserBL(IUserRL userRL)
        {
            this.userRL = userRL;
        }
        public User Authenticate(string Email, string Password)
        {
            try
            {
                return userRL.Authenticate(Email, Password);
            }
            catch (Exception a)
            {
                throw a;
            }
        }

        public User Get(string id)
        {
            try
            {
                return userRL.Get(id);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        public Cart ToCart(Book book, User userModel)
        {
            try
            {
                return userRL.ToCart(book, userModel);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        public WishList ToWishList(Book book, User userModel)
        {
            try
            {
                return userRL.ToWishList(book, userModel);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
    }
}
