// <auto-generated />
using Common_Layer.Models;
using MongoDB.Driver;
using RepositoryLayer.DatabaseSetting;
using RepositoryLayer.Interfaces;
using System;
using System.Collections.Generic;
using System.Text;

namespace RepositoryLayer.Services
{
    public class AdminRL : IAdminRL
    {
        private readonly IMongoCollection<Admin> _admin;

        public AdminRL(IBookstoreDatabaseSettings settings)
        {
            var client = new MongoClient(settings.ConnectionString);
            var database = client.GetDatabase(settings.DatabaseName);

            _admin = database.GetCollection<Admin>(settings.UsersCollectionName);
        }
       

        public Admin Authenticate(string Email, string Password)
        {
            try
            {
                var user = this._admin.Find<Admin>(Admin => Admin.Email == Email && Admin.Password == Password).FirstOrDefault();
                if (user == null)
                {
                    throw null;
                }

                // authentication successful
                return user;
            }
           
            catch (Exception ex)
            {
                throw ex;
            }
        }
    }
}
