// <auto-generated />
using Common_Layer.Models;
using MongoDB.Driver;
using RepositoryLayer.DatabaseSetting;
using RepositoryLayer.Interfaces;
using System;
using System.Collections.Generic;
using System.Text;

namespace RepositoryLayer.Services
{
    public class CartRL : ICartRL
    {
        private readonly IMongoCollection<Orders> _orders;
        private readonly IMongoCollection<Cart> _cart;
        public CartRL(IBookstoreDatabaseSettings settings)
        {
            var client = new MongoClient(settings.ConnectionString);
            var database = client.GetDatabase(settings.DatabaseName);

            _orders = database.GetCollection<Orders>(settings.OrderCollectionName);
            _cart = database.GetCollection<Cart>(settings.CartCollectionName);
        }
        public Orders Create(Orders order)
        {
            this._orders.InsertOne(order);
            return order;
        }

        public dynamic GetCart(string id) =>
            this._cart.Find<Cart>(list => list.UserId == id).ToList();

        public void Remove(string id, string userId) =>
            this._cart.DeleteOne(book => book.BookId == id && book.UserId == userId);
    }
}
