// <auto-generated />
using Common_Layer.Models;
using CommonLayer.Models;
using MongoDB.Driver;
using RepositoryLayer.DatabaseSetting;
using RepositoryLayer.Interfaces;
using System;
using System.Collections.Generic;
using System.Text;

namespace RepositoryLayer.Services
{
    public class UserRL : IUserRL

    {
        private readonly IMongoCollection<User> _users;
        private readonly IMongoCollection<WishList> _wishList;
        private readonly IMongoCollection<Cart> _cart;



        public UserRL(IBookstoreDatabaseSettings settings)
        {
            var client = new MongoClient(settings.ConnectionString);
            var database = client.GetDatabase(settings.DatabaseName);

            _users = database.GetCollection<User>(settings.UsersCollectionName);
            _wishList = database.GetCollection<WishList>(settings.WishListCollectionName);
            _cart = database.GetCollection<Cart>(settings.CartCollectionName);

        }

        public User Authenticate(string Email, string Password)
        {
           
           try
            {
                // var user = this._users.Find<User>(x => x.Email == Email ).FirstOrDefault();
                // var query =from e in this._users.AsQueryable<User>() where e.FirstName == "John" select e;
                if (string.IsNullOrEmpty(Email) || string.IsNullOrEmpty(Password))
                    return null;

                User user = this._users.Find<User>(UserModel => UserModel.Email == Email).FirstOrDefault<User>();

                // check if password is correct
                if (Password != user.Password)
                    return null;



                // check if password is correct


                if (user == null)
                {
                    return  null;
                }

                // authentication successful
                return user;
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        public User Get(string id)
        {
            try
            {
                return this._users.Find<User>(user => user.Id == id).FirstOrDefault();
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        public Cart ToCart(Book book, User userModel)
        {
            try
            {
                Cart cart = new Cart() { BookId = book.Id, Email = userModel.Email, Price = book.Price, Quantity = 1, UserId = userModel.Id };
                this._cart.InsertOne(cart);
                this._wishList.DeleteOne(userandbook => userandbook.UserId == userModel.Id && userandbook.BookId == book.Id);
                return cart;
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        public WishList ToWishList(Book book, User userModel)
        {
            try
            {
                WishList wishlist = new WishList() { BookId = book.Id, Email = userModel.Email, Price = book.Price, UserId = userModel.Id };
                this._wishList.InsertOne(wishlist);
                return wishlist;
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
    }
}
