// <auto-generated />
using BussinessLayer.Interfaces;
using CommonLayer.Models;
using Microsoft.AspNetCore.Cors;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BookStoreApi.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    [EnableCors("AllowOrigin")]
    public class BooksController : ControllerBase
    {
        private readonly IBookBL _bookBL;
        public BooksController(IBookBL _bookBL)
        {
            this._bookBL = _bookBL;
        }

        private List<string> GetTokenType()
        {
            string id = User.FindFirst("Id").Value;
            string type = User.FindFirst("ServiceType").Value;
            List<string> x = new List<string>();
            x.Add(id);
            x.Add(type);
            return x;
        }

        [HttpGet]
        public IActionResult Get()
        {
           var book = _bookBL.Get();
            return this.Ok( new { sucess=true,book});
        }

        [HttpGet("{id:length(24)}", Name = "GetBook")]
        public IActionResult Get(string id)
        {
            var book = _bookBL.Get(id);

            if (book == null)
            {
                return NotFound();
            }

            return this.Ok(new { success = true, book });
        }

        [HttpPost]
        public IActionResult Create(Book book)
        {
            if (GetTokenType()[1] != "Admin")
            {

                return this.BadRequest(new { success = false, message = "Only Admin Allowed" });
            }

            _bookBL.Create(book);

            return this.Ok(new { success = true, message = "Added new Book to data" });
        }

        [HttpPut("{id:length(24)}")]
        public IActionResult Update(string id, Book bookIn)
        {
            if (GetTokenType()[1] != "Admin")
            {

                return this.BadRequest(new { success = false, message = "Only Admin Allowed" });
            }


            var book = _bookBL.Get(id);

            if (book == null)
            {
                return this.BadRequest(new { success = false, message = "Book notfound" });
            }

            _bookBL.Update(id, bookIn);

            return this.Ok(new { success = true, message = "Book Updated" });
        }

        [HttpDelete("{id:length(24)}")]
        public IActionResult Delete(string id)
        {
            if (GetTokenType()[1] != "Admin")
            {

                return this.BadRequest(new { success = false, message = "Only Admin Allowed" });
            }
            var book = _bookBL.Get(id);

            if (book == null)
            {
                return this.BadRequest(new { success = false, message = "Book notfound" });
            }

            _bookBL.Remove(book.Id);

            return this.Ok(new { success = true, message = "Book Deleted" });
        }
        

    }
}
