// <auto-generated />
using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;
using System;

namespace CommonLayer.Models
{
    public class Book
    {
        [BsonId]
        [BsonRepresentation(BsonType.ObjectId)]
        public string Id { get; set; }

        [BsonElement("Name")]
        
        public string BookName { get; set; }

        public decimal Price { get; set; }

        public string Category { get; set; }

        public string Authors { get; set; }

        public DateTime Arrival { get; set; }

        public int AvailableBooks { get; set; }
        public string Description { get; set; }

    }
}
