// <auto-generated />
using Common_Layer.Models;
using System;
using System.Collections.Generic;
using System.Text;

namespace BussinessLayer.Interfaces
{
    public interface IAdminBL
    {
        public Admin Authenticate(string Email, string Password);
    }
}
