// <auto-generated />
using Common_Layer.Models;
using CommonLayer.Models;
using System;
using System.Collections.Generic;
using System.Text;

namespace BussinessLayer.Interfaces
{
    public interface IUserBL
    {
        public User Authenticate(string Email, string Password);

        public User Get(string id);
        public WishList ToWishList(Book book, User userModel);

        public Cart ToCart(Book book, User userModel);
    }
}
