// <auto-generated />
using Common_Layer.Models;
using System;
using System.Collections.Generic;
using System.Text;

namespace RepositoryLayer.Interfaces
{
    public interface IAdminRL
    {
        public Admin Authenticate(string Email, string Password);
    }
}
